### ISSUE TITLE
Documentation of output files

### ISSUE THREAD

**Issue by dotnwat** [databricks/spark-perf#104]
It would be very helpful to have a description of the output results. For instance there is a file in the root of the results directory that seems to summarize the results:

```
$ cat results/mllib_perf_output__2016-05-02_23-03-39
glm-regression, glm-regression --num-trials=10 --inter-trial-wait=3 --num-partitions=1 --random-seed=5 --num-examples=1000 --feature-noise=1.0 --num-features=10000 --num-iterations=20 --step-size=0.001 --reg-type=l2 --reg-param=0.1 --elastic-net-param=0.0 --optimizer=sgd --intercept=0.0 --label-noise=0.1 --loss=l2
Training time: 1.6775, 0.101, 1.596, 1.888, 1.596
Test time: 0.0925, 0.009, 0.074, 0.106, 0.074
Training Set Metric: 31.6423691314, 0.780, 30.9980164059, 33.4544170619, 31.4295866559
Test Set Metric: 33.5374436306, 0.830, 31.7722799916, 33.9670505732, 32.7795578401
glm-classification, glm-classification --num-trials=10 --inter-trial-wait=3 --num-partitions=1 --random-seed=5 --num-examples=1000 --feature-noise=1.0 --num-features=10000 --num-iterations=20 --step-size=0.001 --reg-type=l2 --reg-param=0.1 --elastic-net-param=0.0 --per-negative=0.3 --optimizer=sgd --loss=logistic
Training time: 1.596, 0.099, 1.51, 1.839, 1.51
Test time: 0.079, 0.007, 0.064, 0.085, 0.064
Training Set Metric: 94.1936507186, 0.454, 93.6170212766, 93.6170212766, 94.8275862069
Test Set Metric: 85.1563662824, 2.205, 81.3008130081, 86.3117870722, 85.9848484848
```

As well as the the results JSON string for each experiment in the `*_logs` directory.  I'm assuming the above is a summary, and explaining that would be very useful.

**Comment by JoshRosen** [comment]
See #97:

> See https://github.com/databricks/spark-perf/blob/79f8cfa6494e99a63f7cd4502aea4660b72ff6da/lib/sparkperf/utils.py#L41:
> 
> ```
>     return (result_med, result_std, result_min, result_first, result_last)
> ```

We really should document this somewhere.

**Comment by JoshRosen** [comment]
I just replied to #102 with some pointers regarding the JSON output.

**Comment by dotnwat** [comment]
Thanks Josh that's great.

**Comment by dotnwat** [comment]
@JoshRosen I'm curious about this comment in the test runner, and if it is old or if data generation is still included in the run time...

```
// TODO: generate DataFrame outside of `runTest` so it is not included in timing results
```

https://github.com/databricks/spark-perf/blob/6e4f26de0fcd58b629abb8f5389bb15f914752e7/mllib-tests/v1p5/src/main/scala/mllib/perf/MLAlgorithmTests.scala#L691

EDIT:

copying @feynmanliang do you happen to know?

**Comment by JoshRosen** [comment]
@noahdesu, I'm not sure; I didn't work on any of the ML tests.

**Comment by dotnwat** [comment]
Got it. I'll take a closer look

**Comment by feynmanliang** [comment]
It's still an issue, although I'm unsure how significantly timing results are affected since all that happens is `DataFrame.setMetadata`
