### ISSUE TITLE
Multiple Decision tree test?

### ISSUE THREAD

**Issue by tsailiming** [databricks/spark-perf#45]
Is this to be expected? 

![screen shot 2015-01-21 at 11 01 17 pm](https://cloud.githubusercontent.com/assets/1571401/5838403/344dc65e-a1c2-11e4-958a-3f449729793e.png)

And some cores are zero?

**Comment by mengxr** [comment]
Please check the parameters in `config.py`. They are combinations from single tree/random forest, shallow tree/deep tree, and classification/regression.
