### ISSUE TITLE
Programmatically setting spark-perf configurations is difficult

### ISSUE THREAD

**Issue by nchammas** [databricks/spark-perf#64]
The configuration of a given spark-run is defined by [`config.py`](https://github.com/databricks/spark-perf/blob/1b4dffa7c74b9b4efa83c9d9b3852e179792d2e9/config/config.py.template), which is just a regular Python script.

In addition to defining "base" configurations ([example](https://github.com/databricks/spark-perf/blob/1b4dffa7c74b9b4efa83c9d9b3852e179792d2e9/config/config.py.template#L144)), this script also handles generating derived configurations ([example](https://github.com/databricks/spark-perf/blob/1b4dffa7c74b9b4efa83c9d9b3852e179792d2e9/config/config.py.template#L260-L262))--that is, configurations that are generated automatically from other base or derived configurations.

The combination of configuration-as-Python and derived configurations makes it difficult to programmatically set configurations for a spark-perf run.

What I'm doing now is using `sed` to set the base configurations I want in `config.py`. For example:

```
sed -i -r \
  -e '0,/^(USE_CLUSTER_SPARK = )(True)/s//\1False/' \
  -e '0,/^(DISK_WARMUP = )(False)/s//\1True/' \
  -e 's/\# (JavaOptionSet\("spark.executor.memory", )\["9g"\]\)/\1\["56g"\]\)/' \
  config/config.py
```

This is cumbersome. Is there a better way?

If not, does it make sense to split up `config.py` somehow into a set of base configs and another set of derived configs?

If they are split up like that, one could easily append full Python assignments to the end of the base config file without having to worry about the derived configs missing those new assignments.

Even better, the base configs could be converted to a different format like YAML, which would allow for direct programmatic manipulation of the configs. Simply load the YAML, manipulate it in Python, and then write it back out to YAML.

**Comment by nchammas** [comment]
@JoshRosen / @mengxr Any feedback on this?

I'm thinking next week I'll take a crack at splitting out all the non-derived settings in config.py into a config.yaml, which will then get loaded by config.py.

It's a little clunky organization-wise, but it will let us make these settings programmatically settable without having to change the rest of spark-perf for the time being.

**Comment by alee-altiscale** [comment]
I took the first crack on tweaking the spark-submit options, and notice that the `spark-perf/lib/sparkperf/testsuite.py` hardcoded the references from `spark-perf/config/config.py`. IT looks like there is hardcoded references to config.py so it could be more work then expected.

What I did is simply a string defined in `config.py` to extend the options for `spark-submit`. See example below. This worked fine for my testing and I can extend the executors number as well in YARN mode. I was stuck with 2 executors (default number) all the time without being able to change it in Spark 1.2 (Spark 1.3 can specify dynamic containers, etc)

```
    @classmethod
    def get_spark_submit_cmd(cls, cluster, config, main_class_or_script, opt_list, stdout_filename,
                             stderr_filename):
        spark_submit = "%s/bin/spark-submit" % cluster.spark_home
        cmd = "%s --class %s --master %s --driver-memory %s %s %s %s 1>> %s 2>> %s" % (
            spark_submit, main_class_or_script, config.SPARK_CLUSTER_URL,
            config.SPARK_DRIVER_MEMORY, config.SPARK_SUBMIT_EXTRA_ARGS, cls.test_jar_path, " ".join(opt_list),
            stdout_filename, stderr_filename)
        return cmd
```

I would vote 1 on this change. Not sure if there's a PR for this.

**Comment by nchammas** [comment]
One thing we can perhaps do as part of making spark-perf settings more amenable to programmatic definition is allowing things like executory memory to be defined as a fraction of the host's memory.

That way people can change the instance type they are using for their tests without having to change this setting.

**Comment by nchammas** [comment]
Closing this issue since this project is no longer maintained.
