### ISSUE TITLE
A place from where we can download the jars instead of having to build always

### ISSUE THREAD

**Issue by santoshaditham** [databricks/spark-perf#95]
I want to access the jars directly instead of taking the trouble to build the source. Can you provide a link from where people can download the jars for tests provided by spark-perf ?

Thanks. Btw, I personally think that spark-perf is a great idea executed with brilliance!

**Comment by JoshRosen** [comment]
We don't currently publish the test JARs built by this repo, but it's not hard to compile them yourself since we use a standard SBT build toolchain and project layout.

**Comment by JoshRosen** [comment]
Going to close this as "won't fix" for now; nobody else has asked for this and it's a moderate amount of work to set up.
